task:
  matrix:
    - name: linux
      container:
        image: gcc:latest

    # - name: windows
    #   windows_container:
    #     image: cirrusci/windowsservercore:2016
    #   build_script:
    #     - msbuild libcpuid_vc10.sln /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=v141 /maxcpucount:2 /verbosity:m

    - name: macos
      osx_instance:
        image: mojave-xcode-10.1
      install_script: brew install autoconf automake libtool

    - name: freebsd
      freebsd_instance:
        image: freebsd-12-0-release-amd64
      install_script: pkg install -y autotools

  build_script:
    - libtoolize || glibtoolize
    - autoreconf --install
    - ./configure --prefix=/
    - make -j4

  test_script:
    - make test-old

  publish_script:
    - echo "$CIRRUS_OS"
    - make DESTDIR="$PWD/$CIRRUS_OS" install
