name: Build (UNIX)

on:
  push:
    branches: [ experimental3 ]

jobs:
  build_unix:
    name: Build
    runs-on: ${{ matrix.os.label }}
    strategy:
      matrix:
        os:
          - { label: macos-latest, name: macos }
          - { label: ubuntu-latest, name: linux }

    steps:
    - uses: actions/checkout@v2

    - name: Generate build system
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=""

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: |
        make -C build consistency
        make -C build test-old

    - name: Install
      run: |
        cmake --install build
        install -v AUTHORS ChangeLog COPYING Readme.md "$DESTDIR"
        echo -e "Operating system and compiler version:\n$(uname -a)\n$(cc --version)" "$DESTDIR/Readme.$OSNAME"
      env:
        DESTDIR: installdir
        OSNAME: ${{ matrix.os.name }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os.name }}
        path: installdir/*
