name: Build (UNIX)

on:
  push:
    branches: [ experimental3 ]

jobs:
  build_unix:
    name: Build
    runs-on: ${{ matrix.os.label }}
    strategy:
      matrix:
        os:
          - { label: macos-latest, name: macos }
          - { label: ubuntu-latest, name: linux }

    steps:
    - uses: actions/checkout@v2

    - name: Generate build system
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=""

    - name: Build
      run: cmake --build build

    - name: Install
      run: |
        cmake --install build
        cc --version > "$DESTDIR/Readme.$OSNAME"
        install -v AUTHORS ChangeLog COPYING Readme.md "$DESTDIR"
      env:
        DESTDIR: installdir
        OSNAME: ${{ matrix.os.name }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os.name }}
        path: installdir/*

    - name: Create stable release
      uses: meeDamian/github-release@2.0
      # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        # tag: ${{ env.VERSION }}
        # name: ${{ env.VERSION }}
        tag: continuous
        name: Continuous build
        draft: true
        prerelease: true
        body: |
          Test
        files: >
          installdir/
        gzip: true
        allow_override: true
